### PR TITLE
Better retries

### LINKED ISSUE #5: Submit hangs if the SQS endpoint cannot be reached
We have this when using fake_sqs and the daemon is not started up. It seems that the SDK does something that puts it into a no-timeout request mode, and it would be cool if we could kill that and let it fail non-gracefully if it is unable to connect. Currently it will just cause everything calling in to do a submit do a monumental busy wait.

### PR DESCRIPTION
**Pull request by WJWH**
- Remove RetryWrapper and implement Retriable everywhere it was used.
- Shutdown gracefully when receiving thread dies.
- Add test for closing gracefully on receive error.
- Update version and CHANGELOG.md.

Should fix #5

### CODE REVIEW

File: lib/sqewer/connection.rb [hunk 1]
```diff
@@ -39,14 +39,17 @@ def initialize(queue_url)
...
+  # even after 15 minutes it is either down or the server is misconfigured. Either way it makes no sense to
+  # continue.
   #
   # @return [Array<Message>] an array of Message objects 
   def receive_messages
-    response = client.receive_message(queue_url: @queue_url,
-      wait_time_seconds: DEFAULT_TIMEOUT_SECONDS, max_number_of_messages: 10)
-    response.messages.map do | message |
-      Message.new(message.receipt_handle, message.body)
+    Retriable.retriable on: Seahorse::Client::NetworkingError, tries: MAX_RANDOM_FAILURES_PER_CALL*10 do
```
Comment (julik) [inline lib/sqewer/connection.rb]: Why `*10?`. Could a variable be extracted for this explaining the multiplier at least? Also formatting-wise spaces on both sides of `*` would be appreciated ;-)

File: lib/sqewer/worker.rb [hunk 2]
```diff
@@ -94,22 +97,28 @@ def start
...
-            Thread.pass
+            @logger.debug { "[worker] Cache is full (%d items), postponing receive" % @execution_queue.length }
+            sleep SLEEP_SECONDS_ON_EMPTY_QUEUE
           end
-        else
-          @logger.debug { "[worker] Cache is full (%d items), postponing receive" % @execution_queue.length }
-          sleep SLEEP_SECONDS_ON_EMPTY_QUEUE
+        rescue StandardError => e
+          @logger.fatal "Exiting because message receiving thread died. Exception causing this: #{e.inspect}"
+          this.stop # allow any queues and/or running jobs to complete
```
Comment (julik) [inline lib/sqewer/worker.rb]: I don't know if `stop` is safely reentrant but it's a bit of an edge case. Maybe `this` can be better named `owning_worker` or something because by the time you get to read `this.stop` you already forgot what `this` is  (long methods right?)

File: lib/sqewer/worker.rb [hunk 3]
```diff
@@ -158,7 +167,7 @@ def stop
     true
   end
 
-  # Peforms a hard shutdown by killing all the threads
+  # Performs a hard shutdown by killing all the threads
```
Comment (julik) [inline lib/sqewer/worker.rb]: I really appreciate these
